CREATE TABLE employees (
   id BIGSERIAL PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   cpf CHAR(11) NOT NULL UNIQUE,
   email VARCHAR(100) NOT NULL UNIQUE,
   password VARCHAR(100) NOT NULL,
   role_id BIGINT NOT NULL REFERENCES roles(id),
   clinic_id BIGINT NOT NULL REFERENCES clinics(id),
   is_active BOOLEAN DEFAULT TRUE
);